# Smya dyal l'projet w l'orga f SonarCloud
sonar.projectKey=saraalhane_Skill2Future_
sonar.organization=saraalhane-1

# Fin kayn l'code li bghiti t-analyser (Backend Laravel + Frontend React)
sonar.sources=backend/app,backend/routes,backend/config,backend/database,frontend/src
sonar.tests=backend/tests

# Bach mayb9ach ybrztek 3la l'code dyal vendor awla node_modules
sonar.exclusions=**/vendor/**, **/node_modules/**, backend/public/**, frontend/dist/**, **/*.blade.php

# Kan-wriw l Sonar fin kayn l'rapport dyal tests
sonar.php.coverage.reportPaths=backend/build/logs/clover.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
